# Generated by Django 4.2.5 on 2023-09-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=255)),
                ("batch", models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name="writing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writer_id", models.IntegerField()),
                ("heading", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("image", models.ImageField(upload_to=None)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("AR", "Arabic"),
                            ("EN", "English"),
                            ("ML", "Malayalam"),
                            ("UR", "Urdu"),
                        ],
                        max_length=2,
                    ),
                ),
                ("publishing_date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="author_data",
        ),
        migrations.DeleteModel(
            name="blog_write",
        ),
    ]
