# Generated by Django 4.2.5 on 2023-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_writer_writing_delete_author_data_delete_blog_write"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writer",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="writer",
            name="student_name",
        ),
        migrations.AddField(
            model_name="writer",
            name="writer_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="writing",
            name="category",
            field=models.CharField(
                choices=[
                    ("cat1", "category1"),
                    ("cat2", "category2"),
                    ("cat3", "category3"),
                    ("cat4", "category4"),
                    ("cat5", "category5"),
                    ("cat6", "category6"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
