# Generated by Django 4.2.5 on 2023-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_writer_batch_remove_writer_student_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writing",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
