# Generated by Django 4.2.5 on 2023-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_writing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Aqeeda", "Aqeeda"),
                    ("Fiqh", "Fiqh"),
                    ("History", "History"),
                    ("Interview", "Interview"),
                    ("KvS", "KvS"),
                    ("Language", "Language"),
                    ("Psychology", "Psychology"),
                    ("Politics", "Politics"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
