# Generated by Django 4.2.5 on 2023-09-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_writing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="writing",
            name="sub_category",
            field=models.CharField(
                choices=[
                    ("Aqeeda_01", "Genderstudies"),
                    ("Aqeeda_02", "philosophy"),
                    ("Aqeeda_03", "Science"),
                    ("Aqeeda_04", "Sufism"),
                    ("Aqeeda_05", "Theology"),
                    ("Fiqh_01", "Fiqhulaqalliyyath"),
                    ("Fiqh_02\t", "Madhab"),
                    ("Fiqh_03", "Maqsid"),
                    ("Fiqh_04", "Modernfiqh"),
                    ("Fiqh_05", "Sex/Health/Family"),
                    ("Fiqh_06", "UsoolulFiqh"),
                    ("History_01", "Culture"),
                    ("History_02", "IslamicHistory"),
                    ("History_03", "Malabar"),
                    ("History_04", "Sociology"),
                    ("KvS_01", "Hadees"),
                    ("KvS_02", "IhjazulQuran"),
                    ("KvS_03", "Quran"),
                    ("KvS_04", "Uloomulquran"),
                    ("Language_01", "BookReview"),
                    ("Language_02", "Cinema  Review"),
                    ("Language_03", "Documentary Review"),
                    ("Language_04", "Fiqhulluga"),
                    ("Language_05", "Lahja"),
                    ("Language_06", "Rateric"),
                    ("Language_07", "Translation"),
                    ("Politics_01", "Indian"),
                    ("Politics_02", "International"),
                    ("Politics_03", "Kerala"),
                ],
                default="",
                max_length=25,
            ),
        ),
    ]
