# Generated by Django 4.2.5 on 2023-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_writing_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="writing",
            name="address",
            field=models.TextField(default=""),
        ),
    ]
