# Generated by Django 4.2.4 on 2024-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_writing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='sub_category',
            field=models.CharField(choices=[('Genderstudies', 'Genderstudies'), ('philosophy', 'philosophy'), ('Science', 'Science'), ('Sufism', 'Sufism'), ('Theology', 'Theology'), ('Fiqhulaqalliyyath', 'Fiqhulaqalliyyath'), ('Madhab', 'Madhab'), ('Maqsid', 'Maqsid'), ('Modern fiqh', 'Modern fiqh'), ('Sex/Health/Family', 'Sex/Health/Family'), ('Usoolul Fiqh', 'Usoolul Fiqh'), ('Culture', 'Culture'), ('Islamic History', 'Islamic History'), ('Malabar', 'Malabar'), ('Sociology', 'Sociology'), ('Hadees', 'Hadees'), ('Ihjazul Quran', 'Ihjazul Quran'), ('Quran', 'Quran'), ('Uloomul Quran', 'Uloomul Quran'), ('Book Review', 'Book Review'), ('Cinema  Review', 'Cinema  Review'), ('Documentary Review', 'Documentary Review'), ('Fiqhul Luga', 'Fiqhul Luga'), ('Lahja', 'Lahja'), ('Rateric', 'Rateric'), ('Translation', 'Translation'), ('Indian', 'Indian'), ('International', 'International'), ('Kerala', 'Kerala')], default='', max_length=25),
        ),
    ]
