# Generated by Django 4.2.4 on 2024-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_writing_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='category',
            field=models.CharField(choices=[('Article', 'Article'), ('Essay', 'Essay'), ('Fiction', 'Fiction'), ('Interview', 'Interview'), ('News', 'News'), ('Review', 'Review')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='writing',
            name='sub_category',
            field=models.CharField(choices=[('Book', 'Book'), ('Culture', 'Culture'), ('Gender Studies', 'Gender Studies'), ('History', 'History'), ('International', 'International'), ('Literature', 'Literature'), ('Malabar', 'Malabar'), ('National', 'National'), ('Novel', 'Novel'), ('Philosophy', 'Philosophy'), ('Politics', 'Politics'), ('Religion', 'Religion'), ('Society', 'Society'), ('Story', 'Story'), ('Theology', 'Theology')], default='', max_length=25),
        ),
    ]
