# Generated by Django 4.2.4 on 2024-02-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_writing_category_alter_writing_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='sub_category',
            field=models.CharField(choices=[('Art and Aesthetics', 'Art and Aesthetics'), ('Book', 'Book'), ('Culture', 'Culture'), ('Documentary', 'Documentary'), ('Family', 'Family'), ('Fiqh', 'Fiqh'), ('Gender Studies', 'Gender Studies'), ('Hadees', 'Hadees'), ('History', 'History'), ('International', 'International'), ('Literature', 'Literature'), ('Language', 'Language'), ('Malabar', 'Malabar'), ('Movie', 'Movie'), ('National', 'National'), ('Novel', 'Novel'), ('Philosophy', 'Philosophy'), ('Politics', 'Politics'), ('Quran', 'Quran'), ('Religion', 'Religion'), ('Society', 'Society'), ('Story', 'Story'), ('Theology', 'Theology'), ('Translation', 'Translation'), ('Women', 'Women')], default='', max_length=25),
        ),
    ]
