# Generated by Django 4.2.4 on 2024-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_writing_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='category',
            field=models.CharField(choices=[('Article', 'Article'), ('Essay', 'Essay'), ('Fiction', 'Fiction'), ('Interview', 'Interview'), ('Islamic Studies', 'Islamic Studies'), ('Review', 'Review'), ('Series', 'Series')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='writing',
            name='sub_category',
            field=models.CharField(choices=[('Art and Aesthetics', 'Art and Aesthetics'), ('Book', 'Book'), ('Documentary', 'Documentary'), ('Family', 'Family'), ('Fiqh', 'Fiqh'), ('Hadees', 'Hadees'), ('History and Culture', 'History and Culture'), ('International', 'International'), ('Language and Literature', 'Language and Literature'), ('Malabar', 'Malabar'), ('Movie', 'Movie'), ('National', 'National'), ('Novel', 'Novel'), ('Theology and Philosophy', 'Theology and Philosophy'), ('Politics', 'Politics'), ('Quran', 'Quran'), ('Series 1', 'Series 1'), ('Series 2', 'Series 2'), ('Series 3', 'Series 3'), ('Series 4', 'Series 4'), ('Society', 'Society'), ('Story', 'Story'), ('Translation', 'Translation'), ('Women and Gender', 'Women and Gender')], default='', max_length=25),
        ),
    ]
