# Generated by Django 4.2.4 on 2024-02-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_writing_category_alter_writing_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='article_active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], default='Yes', max_length=3),
        ),
    ]
