# Generated by Django 4.2.4 on 2024-02-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_writing_article_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='article_active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
