# Generated by Django 4.2.4 on 2024-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_writing_article_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='sub_category',
            field=models.CharField(choices=[('Art and Aesthetics', 'Art and Aesthetics'), ('Book', 'Book'), ('Documentary', 'Documentary'), ('Family', 'Family'), ('Fiqh', 'Fiqh'), ('Hadees', 'Hadees'), ('History and Culture', 'History and Culture'), ('History', 'History'), ('International', 'International'), ('Islamic History', 'Islamic History'), ('Islamic Jurisprudence', 'Islamic Jurisprudence'), ('Language and Literature', 'Language and Literature'), ('Malabar', 'Malabar'), ('Movie', 'Movie'), ('National', 'National'), ('Novel', 'Novel'), ('Politics', 'Politics'), ('Quran', 'Quran'), ('Quran and Hadees', 'Quran and Hadees'), ('Series 1', 'Series 1'), ('Series 2', 'Series 2'), ('Series 3', 'Series 3'), ('Series 4', 'Series 4'), ('Society', 'Society'), ('Society and Culture', 'Society and Culture'), ('Story', 'Story'), ('Theology and Philosophy', 'Theology and Philosophy'), ('Translation', 'Translation'), ('Women and Gender', 'Women and Gender')], default='', max_length=25),
        ),
    ]
